### ISSUE TITLE
Allow builders options for envify, to exclude files during `build_runner`

### ISSUE THREAD

**Issue by SunlightBro** [frencojobs/envify#15]
**envify** should most of the time only need to generate one file, but it tries to run on every file , 
(for example if your using `json_serializable` in the same project) 
<details>
  <summary>Output</summary>
  
```sh
...
[INFO] Heartbeat:6.6s elapsed, 17/26 actions completed.
[FINE] envify_generator:envify on lib/utils/union.dart:Running EnvifyGenerator
[FINE] envify_generator:envify on lib/api/model/build_information.dart:Running EnvifyGenerator
[FINE] envify_generator:envify on lib/api/model/azure_subscription.dart:Running EnvifyGenerator
[FINE] envify_generator:envify on lib/api/model/destination.dart:Running EnvifyGenerator
[FINE] envify_generator:envify on lib/api/model/basic_release_details.dart:Running EnvifyGenerator
[FINE] envify_generator:envify on lib/api/model/owner.dart:Running EnvifyGenerator
[FINE] envify_generator:envify on lib/api/model/app.dart:Running EnvifyGenerator
[FINE] envify_generator:envify on lib/api/model/release_details.dart:Running EnvifyGenerator
[INFO] Heartbeat:12.3s elapsed, 25/26 actions completed.
[FINE] envify_generator:envify on lib/state/app_state.dart:Running EnvifyGenerator
```
</details>

While checking and comparing with other builder packages I saw that it is possible to set options in `build.yaml` so I tried it also with **envify** like so:
<details>
  <summary>build.yaml</summary>
  
```YAML
targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          exclude:
            - lib
          include:
            - lib/api/model/*
            - lib/state/app_state.dart
        options:
          explicit_to_json: true
      envify:
        enabled: true
        generate_for:
          exclude:
            - lib
          include:
            - lib/utils/env.dart
```
</details>

But this only shows the following Warning, and still tries to run envify generator over every file.
```sh
pub run build_runner build --delete-conflicting-outputs --verbose
[INFO] Entrypoint:Generating build script...
[INFO] Entrypoint:Generating build script completed, took 631ms
[INFO] Bootstrap:Precompiling build script......
[INFO] Bootstrap:Precompiling build script... completed, took 4.7s
[WARNING] ApplyBuilders:
Configuring `envify:envify` in target `exampler:example` but this is not a known Builder
```
