### ISSUE TITLE
Update analyzer to ^4.0.0 to wotk with Flutter 3.0

### ISSUE THREAD

**Issue by techouse** [frencojobs/envify#27]
In order to work with Flutter 3, we'd need to upgrade [analyzer](https://github.com/dart-lang/sdk/tree/main/pkg/analyzer) to `^4.0.0`.

Seeing that this package looks somewhat abandoned 😭, I've created [my own updated fork here](https://github.com/techouse/envify).

If you need it, use this in your pubspec.yaml

```yaml
dependencies:
  envify: # ^2.0.2
      git:
        url: https://github.com/techouse/envify.git
        ref: main
        path: envify

dev_dependencies:
  envify_generator: # ^2.0.2
      git:
        url: https://github.com/techouse/envify.git
        ref: main
        path: envify_generator
```
