### ISSUE TITLE
Problem with dependency flutter_test: 

### ISSUE THREAD

**Issue by pauli2406** [frencojobs/envify#8]
Hi there.
When integrating this library to my project I am facing the following problem:

_Running "flutter pub get" in app_template...                    
Because envify_generator >=1.1.0 depends on path ^1.8.0-nullsafety.3 and every version of flutter_test from sdk depends on path 1.8.0-nullsafety.1, envify_generator >=1.1.0 is incompatible with flutter_test from sdk._

Is there a workaround which solves this issue?

```
dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner: null
  freezed: ^0.12.2
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.0
  lint: ^1.3.0
  test: ^1.16.0-nullsafety

```

Next to that I also faced this issue. Right now I am using the follwoing environment:
```
environment:
  sdk: ">=2.7.0 <3.0.0"

```
The current Dart SDK version is 2.10.4.
_Because app_template depends on envify >=2.0.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.
pub get failed (1; Because app_template depends on envify >=2.0.0 which requires SDK version >=2.12.0-0 <3.0.0, version solving failed.)
exit code 1_

Regards,
Marcel

**Comment by frencojobs** [comment]
This happens because I've migrated envify fully and envify_generator partially to [sound null-safety](https://dart.dev/null-safety) feature and you are using a lower version of dart+flutter SDK which doesn't support null-safety yet. Not your problem, cause flutter, and its packages are not fully migrated to it yet. It's my false partially that I release it as a major version and not as a prerelease.

You should use the lower versions for now. v2.0.0 and v1.0.6 are all the same except for null-safety.
```yaml
dependencies:
  envify: ^1.0.6
dev_dependencies:
  envify_generator: ^1.0.6
```
Let me know if you still have the problem, and have a nice day.
